version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: jegerenkulbruker
      POSTGRES_PASSWORD: mittkulepassord
      POSTGRES_DB: minkuledatabase
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: jegerenkulbruker
      DB_PASSWORD: mittkulepassord
      DB_NAME: minkuledatabase
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: npm run dev

volumes:
  pgdata: